<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ElementoPP;
use App\Models\Area;
use App\Models\Filtro;

class ElementoPPSeeder extends Seeder
{
    public function run(): void
    {
        $elementos = [
            [
                'nombre' => 'Casco de Seguridad Tipo I Industrial - Minería',
                'descripcion' => 'Casco de Seguridad Tipo I Industrial - Minería para protección de cabeza.​',
                'img_url' => 'img/epp_casco_de_seguridad_tipo_i_industrial_-_minería_agricola_cabeza.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGRICOLA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Cabeza')->first()?->id,
            ],
            [
                'nombre' => 'Casco de Seguridad Tipo I Industrial - Minería',
                'descripcion' => 'Casco de Seguridad Tipo I Industrial - Minería para protección de cabeza.​',
                'img_url' => 'img/epp_casco_de_seguridad_tipo_i_industrial_-_minería_ambiental_cabeza.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AMBIENTAL')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Cabeza')->first()?->id,
            ],
            [
                'nombre' => 'Casco de Seguridad Tipo I Industrial - Minería',
                'descripcion' => 'Casco de Seguridad Tipo I Industrial - Minería para protección de cabeza.​',
                'img_url' => 'img/epp_casco_de_seguridad_tipo_i_industrial_-_minería_comercio_y_servicios_cabeza.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'COMERCIO Y SERVICIOS')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Cabeza')->first()?->id,
            ],
            [
                'nombre' => 'Careta de Esmerilar',
                'descripcion' => 'Careta de Esmerilar para protección de cara.​',
                'img_url' => 'img/epp_careta_de_esmerilar_fic_cara.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'FIC')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Cara')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.​',
                'img_url' => 'img/epp_lentes_de_seguridad_claro_agricola_ojos.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGRICOLA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.​',
                'img_url' => 'img/epp_lentes_de_seguridad_claro_agroindustria_ojos.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGROINDUSTRIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.​',
                'img_url' => 'img/epp_lentes_de_seguridad_claro_ambiental_ojos.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AMBIENTAL')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.​',
                'img_url' => 'img/epp_lentes_de_seguridad_claro_comercio_y_servicios_ojos.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'COMERCIO Y SERVICIOS')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.​',
                'img_url' => 'img/epp_lentes_de_seguridad_claro_confecciones_ojos.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'CONFECCIONES')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.​',
                'img_url' => 'img/epp_lentes_de_seguridad_claro_fic_ojos.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'FIC')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.​',
                'img_url' => 'img/epp_lentes_de_seguridad_claro_pecuaria_ojos.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'PECUARIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Protector Auditivo tipo Copa',
                'descripcion' => 'Protector Auditivo tipo Copa para protección de oidos.​',
                'img_url' => 'img/epp_protector_auditivo_tipo_copa_fic_oidos.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'FIC')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Oidos')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.​',
                'img_url' => 'img/epp_tapabocas_desechable_agricola_sistema_respiratorio.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGRICOLA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.​',
                'img_url' => 'img/epp_tapabocas_desechable_agroindustria_sistema_respiratorio.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGROINDUSTRIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.​',
                'img_url' => 'img/epp_tapabocas_desechable_ambiental_sistema_respiratorio.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AMBIENTAL')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.​',
                'img_url' => 'img/epp_tapabocas_desechable_comercio_y_servicios_sistema_respiratorio.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'COMERCIO Y SERVICIOS')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.​',
                'img_url' => 'img/epp_tapabocas_desechable_confecciones_sistema_respiratorio.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'CONFECCIONES')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.​',
                'img_url' => 'img/epp_tapabocas_desechable_pecuaria_sistema_respiratorio.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'PECUARIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Bata desechable',
                'descripcion' => 'Bata desechable para protección de tronco y cuerpo.​',
                'img_url' => 'img/epp_bata_desechable_agroindustria_tronco_y_cuerpo.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGROINDUSTRIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Tronco y cuerpo')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.​',
                'img_url' => 'img/epp_bota_de_seguridad_tipo_ingeniero_dieléctrica_con_puntera_de_seguridad_agricola_pies_y_piernas.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGRICOLA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.​',
                'img_url' => 'img/epp_bota_de_seguridad_tipo_ingeniero_dieléctrica_con_puntera_de_seguridad_agroindustria_pies_y_piernas.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGROINDUSTRIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.​',
                'img_url' => 'img/epp_bota_de_seguridad_tipo_ingeniero_dieléctrica_con_puntera_de_seguridad_ambiental_pies_y_piernas.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AMBIENTAL')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.​',
                'img_url' => 'img/epp_bota_de_seguridad_tipo_ingeniero_dieléctrica_con_puntera_de_seguridad_comercio_y_servicios_pies_y_piernas.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'COMERCIO Y SERVICIOS')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.​',
                'img_url' => 'img/epp_bota_de_seguridad_tipo_ingeniero_dieléctrica_con_puntera_de_seguridad_fic_pies_y_piernas.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'FIC')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.​',
                'img_url' => 'img/epp_bota_de_seguridad_tipo_ingeniero_dieléctrica_con_puntera_de_seguridad_pecuaria_pies_y_piernas.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'PECUARIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
        ];

        foreach ($elementos as $item) {
            ElementoPP::create($item);
        }
    }
}
