<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ElementoPP;
use App\Models\Area;
use App\Models\Filtro;

class ElementoPPSeeder extends Seeder
{
    public function run(): void
    {
        $elementos = [
            [
                'nombre' => 'Casco de Seguridad Tipo I Industrial - Minería',
                'descripcion' => 'Casco de Seguridad Tipo I Industrial - Minería para protección de cabeza.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGRICOLA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Cabeza')->first()?->id,
            ],
            [
                'nombre' => 'Casco de Seguridad Tipo I Industrial - Minería',
                'descripcion' => 'Casco de Seguridad Tipo I Industrial - Minería para protección de cabeza.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AMBIENTAL')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Cabeza')->first()?->id,
            ],
            [
                'nombre' => 'Casco de Seguridad Tipo I Industrial - Minería',
                'descripcion' => 'Casco de Seguridad Tipo I Industrial - Minería para protección de cabeza.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'COMERCIO Y SERVICIOS')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Cabeza')->first()?->id,
            ],
            [
                'nombre' => 'Careta de Esmerilar',
                'descripcion' => 'Careta de Esmerilar para protección de cara.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'FIC')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Cara')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGRICOLA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGROINDUSTRIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AMBIENTAL')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'COMERCIO Y SERVICIOS')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'CONFECCIONES')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'FIC')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Lentes de Seguridad (Claro)',
                'descripcion' => 'Lentes de Seguridad (Claro) para protección de ojos.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'PECUARIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Ojos')->first()?->id,
            ],
            [
                'nombre' => 'Protector Auditivo tipo Copa',
                'descripcion' => 'Protector Auditivo tipo Copa para protección de oidos.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'FIC')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Oidos')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGRICOLA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGROINDUSTRIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AMBIENTAL')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'COMERCIO Y SERVICIOS')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'CONFECCIONES')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Tapabocas desechable',
                'descripcion' => 'Tapabocas desechable para protección de sistema respiratorio.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'PECUARIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Sistema respiratorio')->first()?->id,
            ],
            [
                'nombre' => 'Bata desechable',
                'descripcion' => 'Bata desechable para protección de tronco y cuerpo.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGROINDUSTRIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Tronco y cuerpo')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGRICOLA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AGROINDUSTRIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'AMBIENTAL')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'COMERCIO Y SERVICIOS')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'FIC')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
            [
                'nombre' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad.',
                'descripcion' => 'Bota de seguridad tipo ingeniero, dieléctrica con puntera de seguridad. para protección de pies y piernas.',
                'img_url' => 'img/default_epp.png',
                'cantidad' => 100,
                'talla' => 'UNICA',
                'areas_id' => Area::where('nombre', 'PECUARIA')->first()?->id,
                'filtros_id' => Filtro::where('parte_del_cuerpo', 'Pies y piernas')->first()?->id,
            ],
        ];

        foreach ($elementos as $item) {
            ElementoPP::create($item);
        }
    }
}
